#!/usr/bin/env bash
# Application-consumer RabbitMQ restart verification for local dev.
# Proves woodpantry-recipes resumes consuming recipe.imported after its
# service container is stopped, a persistent event is queued, and the service
# is started again.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib.sh"

require_jq

export RABBIT_HTTP_URL="${RABBIT_HTTP_URL:-http://localhost:15672/api}"
export RABBITMQ_USER="${RABBITMQ_USER:-woodpantry}"
export RABBITMQ_PASS="${RABBITMQ_PASS:-woodpantry}"
export COMPOSE_ENGINE="${COMPOSE_ENGINE:-podman}"
export COMPOSE_FILE="${COMPOSE_FILE:-$REPO_ROOT/local/docker-compose.yaml}"
export COMPOSE_ENV_FILE="${COMPOSE_ENV_FILE:-$REPO_ROOT/local/.env}"

rabbit_api() {
    local method="$1"
    local path="$2"
    local body="${3:-}"

    if [[ -n "$body" ]]; then
        curl -s -u "${RABBITMQ_USER}:${RABBITMQ_PASS}" \
            -X "$method" \
            -H "Content-Type: application/json" \
            "$RABBIT_HTTP_URL$path" \
            -d "$body"
        return
    fi

    curl -s -u "${RABBITMQ_USER}:${RABBITMQ_PASS}" -X "$method" "$RABBIT_HTTP_URL$path"
}

compose() {
    "$COMPOSE_ENGINE" compose -f "$COMPOSE_FILE" --env-file "$COMPOSE_ENV_FILE" "$@"
}

get_queue() {
    local queue_name="$1"
    rabbit_api GET "/queues/%2F/${queue_name}"
}

get_messages() {
    local queue_name="$1"
    local count="${2:-1}"
    rabbit_api POST "/queues/%2F/${queue_name}/get" "$(jq -nc --argjson count "$count" '{count: $count, ackmode: "ack_requeue_false", encoding: "auto", truncate: 50000}')"
}

peek_messages() {
    local queue_name="$1"
    local count="${2:-1}"
    rabbit_api POST "/queues/%2F/${queue_name}/get" "$(jq -nc --argjson count "$count" '{count: $count, ackmode: "ack_requeue_true", encoding: "auto", truncate: 50000}')"
}

publish_message() {
    local routing_key="$1"
    local payload="$2"
    rabbit_api POST "/exchanges/%2F/woodpantry.topic/publish" "$(jq -nc --arg key "$routing_key" --arg payload "$payload" '{properties: {delivery_mode: 2, content_type: "application/json"}, routing_key: $key, payload: $payload, payload_encoding: "string"}')"
}

rabbitmq_ready() {
    local overview
    overview="$(rabbit_api GET "/overview")" || return 1
    echo "$overview" | jq -e '.rabbitmq_version | length > 0' > /dev/null 2>&1
}

queue_exists() {
    local queue_name="$1"
    [[ "$(get_queue "$queue_name" | jq -r '.name // empty')" == "$queue_name" ]]
}

service_healthy() {
    local url="$1"
    curl -fsS "$url/healthz" > /dev/null 2>&1
}

queue_has_ready_messages() {
    local queue_name="$1"
    [[ "$(get_queue "$queue_name" | jq -r '.messages_ready // 0')" -ge 1 ]]
}

drain_recipe_import_request_for_job() {
    local job_id="$1"
    local queue_name="ingestion.recipe-import-requested"
    local messages
    local payload_job_id

    # The ingestion service is stopped before POST /recipes/ingest, so the one
    # request generated by this smoke test should be waiting in the durable
    # ingestion queue. Acknowledging it prevents the cleanup restart from doing
    # an unnecessary live extraction for this synthetic job.
    messages="$(peek_messages "$queue_name" 1)"
    if ! echo "$messages" | jq -e 'length == 1' > /dev/null 2>&1; then
        log_skip "No recipe.import.requested message was available to drain for cleanup isolation"
        return 0
    fi

    payload_job_id="$(echo "$messages" | jq -r '.[0].payload | fromjson | .job_id // empty')"
    if [[ "$payload_job_id" != "$job_id" ]]; then
        log_skip "Old recipe.import.requested message is ahead of this test's job; leaving queue intact"
        return 0
    fi

    messages="$(get_messages "$queue_name" 1)"
    payload_job_id="$(echo "$messages" | jq -r '.[0].payload | fromjson | .job_id // empty')"
    if [[ "$payload_job_id" == "$job_id" ]]; then
        log_success "Drained this test's recipe.import.requested event while ingestion is stopped"
        return 0
    fi

    log_skip "Unable to drain this test's recipe.import.requested event after non-destructive peek; leaving queue state as-is"
    return 0
}

wait_for_job_staged() {
    local job_id="$1"
    local attempts="${2:-40}"
    local status=""
    local response=""

    for _ in $(seq 1 "$attempts"); do
        response="$(api_get "$REC_URL/recipes/ingest/$job_id" '200,202' || true)"
        status="$(echo "$response" | jq -r '.status // .Status // empty' 2>/dev/null || true)"

        case "$status" in
            staged|ready|ready_for_review)
                printf '%s\n' "$response"
                return 0
                ;;
            failed)
                printf '%s\n' "$response"
                return 2
                ;;
        esac

        sleep 1
    done

    printf '%s\n' "$response"
    return 1
}

INGESTION_STOPPED=0
RECIPES_STOPPED=0

cleanup() {
    if [[ "$RECIPES_STOPPED" -eq 1 ]]; then
        compose start recipes > /dev/null 2>&1 || true
    fi
    if [[ "$INGESTION_STOPPED" -eq 1 ]]; then
        compose start ingestion > /dev/null 2>&1 || true
    fi
}

trap cleanup EXIT

REQUEST_QUEUE="ingestion.recipe-import-requested"
IMPORTED_QUEUE="recipes.recipe-imported"
RECIPE_TITLE="$(unique_name "Smoke Restart Consumer Soup")"
FREE_TEXT=$(cat <<EOF
${RECIPE_TITLE}

Ingredients:
- 1 cup restart-test beans
- 2 tsp restart-test oil

Instructions:
Warm the beans with oil and serve.
EOF
)

log_step "RabbitMQ App Consumer Restart — Preflight"

if wait_until rabbitmq_ready 60 2; then
    log_success "RabbitMQ management API is reachable"
else
    log_fail "RabbitMQ management API is not reachable"
    smoke_summary
    exit $?
fi

for queue_name in "$REQUEST_QUEUE" "$IMPORTED_QUEUE"; do
    if wait_until "queue_exists \"$queue_name\"" 30 2; then
        log_success "Queue ${queue_name} exists"
    else
        log_fail "Queue ${queue_name} does not exist; start the full local stack before running this opt-in test"
        smoke_summary
        exit $?
    fi
    QUEUE_RESP="$(get_queue "$queue_name")"
    assert_json_expr "$QUEUE_RESP" '.durable == true' "Queue ${queue_name} is durable"
done

if service_healthy "$REC_URL"; then
    log_success "Recipe service is healthy before restart probe"
else
    log_fail "Recipe service is not healthy before restart probe"
    smoke_summary
    exit $?
fi

log_step "RabbitMQ App Consumer Restart — Create Job With Ingestion Stopped"

if compose stop ingestion > /dev/null; then
    INGESTION_STOPPED=1
    log_success "Stopped ingestion service to prevent real extraction races"
else
    log_fail "Failed to stop ingestion service"
    smoke_summary
    exit $?
fi

INGEST_RESP="$(api_post "$REC_URL/recipes/ingest" "$(jq -nc --arg text "$FREE_TEXT" '{text: $text}')" '200,201,202')" || {
    log_fail "POST /recipes/ingest failed while creating restart probe job. Response: $INGEST_RESP"
    smoke_summary; exit $?
}

JOB_ID="$(extract_json "$INGEST_RESP" '.job_id // .jobID // .id // .ID')"
if [[ -z "$JOB_ID" ]]; then
    log_fail "No job ID returned from recipe ingest. Response: $INGEST_RESP"
    smoke_summary
    exit $?
fi
log_success "Recipe ingest created restart probe job $JOB_ID"

if wait_until "queue_has_ready_messages \"$REQUEST_QUEUE\"" 20 1; then
    drain_recipe_import_request_for_job "$JOB_ID" || {
        smoke_summary
        exit $?
    }
else
    log_skip "recipe.import.requested did not become ready before drain; continuing with synthetic imported event"
fi

log_step "RabbitMQ App Consumer Restart — Queue Event While Recipes Is Stopped"

if compose stop recipes > /dev/null; then
    RECIPES_STOPPED=1
    log_success "Stopped recipes service before publishing recipe.imported"
else
    log_fail "Failed to stop recipes service"
    smoke_summary
    exit $?
fi

STAGED_DATA="$(jq -nc \
    --arg title "$RECIPE_TITLE" \
    '{
        title: $title,
        description: "Synthetic recipe.imported payload for consumer restart smoke test",
        servings: 1,
        prep_minutes: 1,
        cook_minutes: 5,
        tags: ["smoke", "rabbitmq", "restart"],
        steps: ["Warm the beans with oil and serve."],
        ingredients: [
            {name: "restart-test beans", quantity: 1, unit: "cup", is_optional: false},
            {name: "restart-test oil", quantity: 2, unit: "tsp", is_optional: false}
        ]
    }')"
EVENT_PAYLOAD="$(jq -nc --arg job_id "$JOB_ID" --argjson staged_data "$STAGED_DATA" '{job_id: $job_id, status: "staged", staged_data: $staged_data}')"

PUBLISH_RESP="$(publish_message "recipe.imported" "$EVENT_PAYLOAD")"
assert_json_expr "$PUBLISH_RESP" '.routed == true' "Synthetic recipe.imported event was routed while recipes was stopped"

if wait_until "queue_has_ready_messages \"$IMPORTED_QUEUE\"" 20 1; then
    log_success "Synthetic recipe.imported event is waiting in recipes queue"
else
    log_fail "Synthetic recipe.imported event did not appear as ready in recipes queue"
    smoke_summary
    exit $?
fi

log_step "RabbitMQ App Consumer Restart — Restart Recipes And Verify Consumption"

if compose start recipes > /dev/null; then
    RECIPES_STOPPED=0
    log_success "Started recipes service after queuing recipe.imported"
else
    log_fail "Failed to start recipes service"
    smoke_summary
    exit $?
fi

if wait_until "service_healthy \"$REC_URL\"" 60 2; then
    log_success "Recipe service is healthy after restart"
else
    log_fail "Recipe service did not become healthy after restart"
    smoke_summary
    exit $?
fi

set +e
FINAL_JOB_RESP="$(wait_for_job_staged "$JOB_ID" 40)"
WAIT_RC=$?
set -e
if [[ "$WAIT_RC" -eq 0 ]]; then
    log_success "Recipe service consumed queued recipe.imported after restart and staged the job"
elif [[ "$WAIT_RC" -eq 2 ]]; then
    log_fail "Recipe job entered failed state after restart. Response: $FINAL_JOB_RESP"
    smoke_summary
    exit $?
else
    log_fail "Recipe job did not become staged after recipes restart. Last response: $FINAL_JOB_RESP"
    smoke_summary
    exit $?
fi

FINAL_STATUS="$(extract_json "$FINAL_JOB_RESP" '.status // .Status')"
FINAL_TITLE="$(extract_json "$FINAL_JOB_RESP" '.staged_data.title // .StagedData.title')"

if [[ "$FINAL_STATUS" == "staged" || "$FINAL_STATUS" == "ready" || "$FINAL_STATUS" == "ready_for_review" ]]; then
    log_success "Restart probe job status is $FINAL_STATUS"
else
    log_fail "Unexpected restart probe job status '$FINAL_STATUS'. Response: $FINAL_JOB_RESP"
fi

if [[ "$FINAL_TITLE" == "$RECIPE_TITLE" ]]; then
    log_success "Restart probe staged data title matches the synthetic event"
else
    log_fail "Restart probe staged data title mismatch. Expected '$RECIPE_TITLE', response: $FINAL_JOB_RESP"
fi

smoke_summary
